// Service Worker
export const RECEIVE_SERVICEWORKER_REGISTRATION = 'RECEIVE_SERVICEWORKER_REGISTRATION';
export const RECEIVE_PUSH_SUBSCRIPTION = 'RECEIVE_PUSH_SUBSCRIPTION';

// Calls
export const REQUEST_CALLS = 'REQUEST_CALLS';
export const RECEIVE_CALLS = 'RECEIVE_CALLS';
export const RECEIVE_CALLS_FAILURE = 'RECEIVE_CALLS_FAILURE';

// Auth
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';

// User
export const REQUEST_USER = 'REQUEST_USER';
export const RECIEVE_USER = 'RECIEVE_USER';
export const REQUEST_CREATE_USER = 'REQUEST_CREATE_USER';
export const RECEIVE_CREATE_USER = 'RECEIVE_CREATE_USER';
export const RECEIVE_CREATE_USER_FAILURE = 'RECEIVE_CREATE_USER_FAILURE';
