// Service Worker
export const RECEIVE_SERVICEWORKER_REGISTRATION = 'RECEIVE_SERVICEWORKER_REGISTRATION';

// Messages
export const REQUEST_MESSAGE_AUDIO = 'REQUEST_MESSAGE_AUDIO';
export const RECEIVE_MESSAGE_AUDIO = 'RECEIVE_MESSAGE_AUDIO';
export const CLEAR_ACTIVE_MESSAGE = 'CLEAR_ACTIVE_MESSAGE';
export const REQUEST_MESSAGES = 'REQUEST_MESSAGES';
export const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES';
export const RECEIVE_MESSAGES_FAILURE = 'RECEIVE_MESSAGES_FAILURE';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
export const REQUEST_POST_MESSAGE = 'REQUEST_POST_MESSAGE';
export const RECEIVE_POST_MESSAGE = 'RECEIVE_POST_MESSAGE';
export const RECEIVE_POST_MESSAGE_FAILURE = 'RECEIVE_POST_MESSAGE_FAILURE';
export const START_NEW_MESSAGE_AUDIO = 'START_NEW_MESSAGE_AUDIO';

// Conversations
export const REQUEST_CONVERSATIONS = 'REQUEST_CONVERSATIONS';
export const RECEIVE_CONVERSATIONS = 'RECEIVE_CONVERSATIONS';
export const RECEIVE_CONVERSATIONS_FAILURE = 'RECEIVE_CONVERSATIONS_FAILURE';
export const REQUEST_ACTIVE_CONVERSATION = 'REQUEST_ACTIVE_CONVERSATION';
export const RECEIVE_ACTIVE_CONVERSATION_FAILURE = 'RECEIVE_ACTIVE_CONVERSATION_FAILURE';
export const RECEIVE_ACTIVE_CONVERSATION = 'RECEIVE_ACTIVE_CONVERSATION';

// Auth
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const AUTH_CODE_REQUESTED = 'AUTH_CODE_REQUESTED';

// User
export const REQUEST_USERS = 'REQUEST_USERS';
export const RECIEVE_USERS = 'RECIEVE_USERS';
export const REQUEST_CREATE_USER = 'REQUEST_CREATE_USER';
export const RECEIVE_CREATE_USER = 'RECEIVE_CREATE_USER';
export const RECEIVE_CREATE_USER_FAILURE = 'RECEIVE_CREATE_USER_FAILURE';
export const REQUEST_DELETE_USER = 'REQUEST_DELETE_USER';
export const RECEIVE_DELETE_USER = 'RECEIVE_DELETE_USER';
export const RECEIVE_DELETE_USER_FAILURE = 'RECEIVE_DELETE_USER_FAILURE';

// Notifications
export const RECEIVE_PUSH_MANAGER = 'RECEIVE_PUSH_MANAGER';
export const RECEIVE_CLIENT_PUSH_SUBSCRIPTION = 'RECEIVE_CLIENT_PUSH_SUBSCRIPTION';
export const RECEIVE_SERVER_PUSH_SUBSCRIPTION = 'RECEIVE_SERVER_PUSH_SUBSCRIPTION';
