// Service Worker
export const RECEIVE_SERVICEWORKER_REGISTRATION = 'RECEIVE_SERVICEWORKER_REGISTRATION';

// Calls
export const REQUEST_CALL_AUDIO = 'REQUEST_CALL_AUDIO';
export const RECEIVE_CALL_AUDIO = 'RECEIVE_CALL_AUDIO';
export const CLEAR_ACTIVE_CALL = 'CLEAR_ACTIVE_CALL';
export const REQUEST_CALLS = 'REQUEST_CALLS';
export const RECEIVE_CALLS = 'RECEIVE_CALLS';
export const RECEIVE_CALLS_FAILURE = 'RECEIVE_CALLS_FAILURE';
export const CLEAR_CALLS = 'CLEAR_CALLS';
export const REQUEST_POST_MESSAGE = 'REQUEST_POST_MESSAGE';
export const RECEIVE_POST_MESSAGE = 'RECEIVE_POST_MESSAGE';
export const RECEIVE_POST_MESSAGE_FAILURE = 'RECEIVE_POST_MESSAGE_FAILURE';
export const START_NEW_CALL_AUDIO = 'START_NEW_CALL_AUDIO';

// Conversations
export const REQUEST_CONVERSATIONS = 'REQUEST_CONVERSATIONS';
export const RECEIVE_CONVERSATIONS = 'RECEIVE_CONVERSATIONS';
export const RECEIVE_CONVERSATIONS_FAILURE = 'RECEIVE_CONVERSATIONS_FAILURE';
export const RECEIVE_CONVERSATION_FAILURE = 'RECEIVE_CONVERSATION_FAILURE';
export const SET_ACTIVE_CONVERSATION = 'SET_ACTIVE_CONVERSATION';

// Auth
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const AUTH_CODE_REQUESTED = 'AUTH_CODE_REQUESTED';

// User
export const REQUEST_USERS = 'REQUEST_USERS';
export const RECIEVE_USERS = 'RECIEVE_USERS';
export const REQUEST_CREATE_USER = 'REQUEST_CREATE_USER';
export const RECEIVE_CREATE_USER = 'RECEIVE_CREATE_USER';
export const RECEIVE_CREATE_USER_FAILURE = 'RECEIVE_CREATE_USER_FAILURE';
export const REQUEST_DELETE_USER = 'REQUEST_DELETE_USER';
export const RECEIVE_DELETE_USER = 'RECEIVE_DELETE_USER';
export const RECEIVE_DELETE_USER_FAILURE = 'RECEIVE_DELETE_USER_FAILURE';

// Notifications
export const RECEIVE_PUSH_MANAGER = 'RECEIVE_PUSH_MANAGER';
export const RECEIVE_CLIENT_PUSH_SUBSCRIPTION = 'RECEIVE_CLIENT_PUSH_SUBSCRIPTION';
export const RECEIVE_SERVER_PUSH_SUBSCRIPTION = 'RECEIVE_SERVER_PUSH_SUBSCRIPTION';
